name: stitch_core
description: The Core Stitch SDK in Dart
version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  bson: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter