name: stitch_mobile
description: Flutter Stitch SDK
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  stitch_core:
    path: ../stitch_core
  shared_preferences: ^0.5.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter